{% set name = "diffpy.structure" %}
{% set version = "3.0.1" %}
{% set sha256 = "eed3367701e8d4b49db1132fe09c9fb7f4e0ea4e575f0ace2bd8825e537864f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  preserve_egg_dir: True
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - numpy
    - pycifrw
    - six

test:
  imports:
    - diffpy
    - diffpy.structure
    - diffpy.structure.parsers
    - diffpy.structure.applications
    - diffpy.structure.expansion
    - diffpy.structure.tests
    # legacy imports
    - diffpy.Structure
    - diffpy.Structure.Parsers
    - diffpy.Structure.applications
    - diffpy.Structure.expansion
    - diffpy.Structure.tests

about:
  home: https://github.com/diffpy/diffpy.structure
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Crystal structure container and parsers for structure formats.

  description: |
    The diffpy.Structure package provides objects for storing atomic
    coordinates, displacement parameters and other crystal structure data.
    diffpy.Structure supports import and export of structure data in several
    structure formats such as CIF, PDB, xyz. It provides conversion between
    fractional and absolute Cartesian coordinates, functions for symmetry
    expansion from asymmetric unit and generation of symmetry constraints for
    atom positions and displacement parameters. diffpy.Structure includes
    definitions of all space groups in over 500 symmetry settings.
  doc_url: http://www.diffpy.org/diffpy.structure/
  dev_url: https://github.com/diffpy/diffpy.structure

extra:
  recipe-maintainers:
    - CJ-Wright
    - pavoljuhas
    - st3107
    - sbillinge
