{% set name = "diffpy.structure" %}
{% set version = "3.2.2rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_structure/diffpy_structure-{{ version }}.tar.gz
  sha256: 8dc4bdf665c939f985d4f956ae966e1fb0585e2662bd0dff8f7cde8edeafa550

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >=3.10
    - numpy
    - pycifrw >=4.4.3

test: 
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.structure/
  license: Free To Use But Restricted
  license_file: LICENSE.rst
  summary: Crystal structure container and parsers for structure formats.
  description: |
    The diffpy.Structure package provides objects for storing atomic
    coordinates, displacement parameters and other crystal structure data.
    diffpy.Structure supports import and export of structure data in several
    structure formats such as CIF, PDB, xyz. It provides conversion between
    fractional and absolute Cartesian coordinates, functions for symmetry
    expansion from asymmetric unit and generation of symmetry constraints for
    atom positions and displacement parameters. diffpy.Structure includes
    definitions of all space groups in over 500 symmetry settings.
  doc_url: http://www.diffpy.org/diffpy.structure/
  dev_url: https://github.com/diffpy/diffpy.structure

extra:
  recipe-maintainers:
    - bobleesj
    - dragonyanglong
    - pavoljuhas
    - st3107
    - sbillinge
