{% set name = "diffpy.structure" %}
{% set version = "3.2.0" %}
{%- set sha256 = "931da51620a660959d5d7192a781f4e21a91a78174ebe371787f42ba4759af7a" -%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_structure/diffpy_structure-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools

  run:
    - python >=3.10
    - setuptools
    - numpy <2.0.0
    - pycifrw >=4.4.3

test:
  imports:
    - diffpy
    - diffpy.structure
    - diffpy.structure.parsers
    - diffpy.structure.applications
    - diffpy.structure.expansion
    - diffpy.structure.tests

  requires:
    - pytest

about:
  home: https://github.com/diffpy/diffpy.structure/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Crystal structure container and parsers for structure formats.
  description: |
    The diffpy.Structure package provides objects for storing atomic
    coordinates, displacement parameters and other crystal structure data.
    diffpy.Structure supports import and export of structure data in several
    structure formats such as CIF, PDB, xyz. It provides conversion between
    fractional and absolute Cartesian coordinates, functions for symmetry
    expansion from asymmetric unit and generation of symmetry constraints for
    atom positions and displacement parameters. diffpy.Structure includes
    definitions of all space groups in over 500 symmetry settings.
  doc_url: http://www.diffpy.org/diffpy.structure/
  dev_url: https://github.com/diffpy/diffpy.structure

extra:
  recipe-maintainers:
    - dragonyanglong
    - pavoljuhas
    - st3107
    - sbillinge
